= amdgpuoc

A  lightweight CLI utility to overclock AMD GPUs.

For more information about the amdgpu driver and overclocking:
https://www.kernel.org/doc/html/latest/gpu/amdgpu.html

For more information about the amdgpu.ppfeaturemask parameter:
`drivers/gpu/drm/amd/include/amd_shared.h`
from the kernel source tree.

Not all AMD GPUs can be overclocked in this manner.

== Warning

Research your own GPU
and adjust the *.conf file as needed before running this utility.
Overclocking can cause instability and damage to hardware.

== Usage

`amdgpuoc [file...]`

If no arguments are given,
amdgpuoc uses the system-wide *.conf file.
Otherwise any arguments are treated as user-specified *.conf files.
Specifying an argument as `-` uses STDIN for input.

== Requirements

* An AMD GPU
* Linux kernel >= 4.20
* Kernel parameter `amdgpu.ppfeaturemask=0xffffffff`
* POSIX `awk`

== Installation

. In `/etc/default/grub`,
  add `amdgpu.ppfeaturemask=0xffffffff`
  to `GRUB_CMDLINE_LINUX_DEFAULT`.
. `grub2-mkconfig -o /boot/grub2/grub.cfg`
. `make install [prefix=path]`
. `systemctl enable amdgpuoc`
. Reboot.

== Configuration

To configure values,
edit `/usr/local/etc/amdgpuoc.conf`.
See the included *.conf file for details.
